app:
  global:
    labels:
      app: sschool

  defaultPodOptions:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000

  controllers:
    main:
      type: deployment
      replicas: 1
      containers:
        app:
          image:
            repository: ghcr.io/adorsys-gis/sschool
            tag: 2025.4.1
            pullPolicy: IfNotPresent

          # -- ConfigMap to be loaded as environment variables
          envFrom:
            - configMapRef:
                name: '{{ .Release.Name }}-config'
            - secretRef:
                name: '{{ .Release.Name }}-s3'
            - secretRef:
                name: '{{ .Release.Name }}-otel'
            - secretRef:
                name: '{{ .Release.Name }}-auth'
            - secretRef:
                name: '{{ .Release.Name }}-db'
            - secretRef:
                name: '{{ .Release.Name }}-ai'

  service:
    app:
      enabled: true
      annotations: {}
      nameOverride: service
      type: ClusterIP
      controller: main
      ports:
        http:
          enabled: true
          port: 3000
          targetPort: 3000

  ingress:
    app:
      enabled: true
      annotations: {}
      nameOverride: ingress
      #className: 'nginx'
      hosts:
        - host: sschool.example.com
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: app
                port: http
      tls:
        - secretName: sschool-example-com-secret
          hosts:
            - sschool.example.com

  configMaps:
    config:
      enabled: true
      annotations:
        description: 'Common configuration for the GIS Application app.'
      data:
        AUTH_KEYCLOAK_ISSUER: https://kec.example.com/realms/main

        AUTH_SESSION_MAX_AGE: '2592000'
        AUTH_SESSION_UPDATE_AGE: '2592000'

        S3_ENDPOINT: s3.example.com
        S3_PORT: '443'
        S3_SCHEME: https
        S3_BUCKET: sschool
        S3_CDN_URL: https://s3.example.com

  secrets:
    s3:
      enabled: true
      annotations:
        description: 'S3 configuration for the GIS Application app.'
      stringData:
        S3_ACCESS_KEY: 'minio'
        S3_SECRET_KEY: 'minio123'
    otel:
      enabled: true
      annotations:
        description: 'OTEL configuration for the GIS Application app.'
      stringData:
        OTEL_EXPORTER_OTLP_ENDPOINT: 'https://otel.example.com'
    auth:
      enabled: true
      annotations:
        description: 'Auth configuration for the GIS Application app.'
      stringData:
        AUTH_SECRET: 'gfhZ+94pqhGDi03RCD/6klIbTd92V5yA8G+oEN9c6pk='
        AUTH_KEYCLOAK_ID: 'sschool'
        AUTH_KEYCLOAK_SECRET: 'someSecret'
    db:
      enabled: true
      annotations:
        description: 'Auth configuration for the GIS Application app.'
      stringData:
        DATABASE_URL: 'postgresql+ssl://gisapply:gisapply-password@localhost:5432/gisapply?schema=public'
    ai:
      stringData:
        OPENAI_KEY: ""
        OPENAI_URL: ""
        
        OPENAI_MAX_TOKENS: "1000"
        OPENAI_PAGE_DESCRIPTION_MAX_TOKEN: "50"
        OPENAI_PAGE_LAYOUT_MODEL: "gpt-4o"
        OPENAI_PAGE_CONTENT_MODEL: "gemini-2.0-flash-lite"

  networkpolicies:
    main:
      enabled: true
      controller: main
      policyTypes:
        - Ingress
      rules:
        ingress:
          - from:
              - podSelector:
                  matchLabels:
                    app: sschool
            ports:
              - protocol: TCP
                port: 3000
